name: Preview

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  preview:
    name: Publish Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup and install
        uses: ./.github/actions/setup

      - name: Build packages
        run: pnpm turbo run build --filter="./packages/*"

      - name: Publish Preview
        run: pnpm dlx pkg-pr-new publish --compact './packages/*'
